### ISSUE TITLE
Thermal Expansion Sawmill does not produce planks but produces Chopping Block instead

### ISSUE THREAD

**Issue by BillboardEric** [codetaylor/pyrotech#17]
Sawmill should be outputting planks with the vanilla woods but don't. Noticed it is only with the currently implemented woods that it has a problem with. (Biomes O Plenty wood works correctly in the sawmill)

![image](https://user-images.githubusercontent.com/8685981/59534527-92d5ed00-8ebc-11e9-8e98-0e92d52a1459.png)

**Comment by codetaylor** [comment]
I'm pretty sure that this is because, by default, Pyrotech (Pt) removes the vanilla wood / plank and plank / slab recipes in order to force the player to use the chopping block and sawmill.

To keep Pt's default functionality, you'll have to:
* remove the TE recipe indicated in the picture otherwise it will match all <ore:logWood> inputs
* add the vanilla woods back to TE using CrT or whatever it uses to define recipes

An alternative is to go into the Pt core config and remove the wood recipes from the list of recipes that Pt removes on startup. This would probably work, but it would mean that players can then just craft the wood and wouldn't be forced to use the other mechanics.

If there's no way to remove the recipe indicated in the picture, then I guess one possible solution to that would be to change Pt's default recipe for the chopping block to include another item, like a crude axe.
