### ISSUE TITLE
Couldn't be together with From The Ground Up

### ISSUE THREAD

**Issue by God-Arthur** [codetaylor/pyrotech#186]
(My English is not good)
  Hello,I'm a mods pack maker from China.Nowadays I found that your mod made the mod From The Ground Up couldn't work.It's a recipes unlocking mod,after pyrotech setup,the research_table of FTGU didn't work.Before that,all machines worked normally,normally and normally.Why was that?Have you banned something with research,with recipes unlocking?Or do you have any methods of resolution?Help me,please!I'll thank you very much!

**Comment by codetaylor** [comment]
My first guess is the problem is happening because Pyrotech removes some vanilla recipes. If FTGU relies on having those recipes, it would probably break something.

The list of recipes that Pyrotech removes is configurable and is located in `core.cfg` -> `recipes`. Pyrotech currently removes a number of crafting recipes as well as one furnace recipe.

**Comment by God-Arthur** [comment]
I think you don't understand I mean...Research_table is a independent machine that added by FTGU,some recipes need to be unlocked by it.For example,I'm unlocking the recipe of brick_block,and I need to connect Terracotta_tile and brick_block with three items.The key is clay_block → clay → brick.But now,two adjacent lattice couldn't be both filled.Why?I'll give you a picture later

**Comment by God-Arthur** [comment]
![work normally without Pyrotech](https://user-images.githubusercontent.com/42578454/64469080-f049a500-d15e-11e9-9c15-0975f0bf9f13.png)
![the research_table](https://user-images.githubusercontent.com/42578454/64469084-f6d81c80-d15e-11e9-84e9-a76ff4c59440.png)
![couldn't set in - 1](https://user-images.githubusercontent.com/42578454/64469087-fc356700-d15e-11e9-9acc-fb28726917ca.png)
![couldn't set in - 2](https://user-images.githubusercontent.com/42578454/64469088-00618480-d15f-11e9-8b4f-b8b797d6be95.png)
![couldn't set in - 3](https://user-images.githubusercontent.com/42578454/64469089-035c7500-d15f-11e9-8d80-bcc6c1ad086d.png)

**Comment by codetaylor** [comment]
This is happening because Pyrotech removes some recipes, specifically the Brick recipe.

The research `ftgu:construction/brickwork` indicates that it uses the `ftgu:connect` research type:
https://github.com/Astavie/From-the-Ground-Up/blob/1.12/src/main/resources/assets/ftgumod/technologies/construction/brickwork.json#L27

The connection puzzle works by connecting the item on the left with the one on the right *using items that are used to make the other.*

From the [CurseForge project page](https://www.curseforge.com/minecraft/mc-mods/from-the-ground-up):
> In the connecting puzzle, you see an item to the left and an item to the right. You need to connect them with 3 items in between. Items connect if one item is used to make the other.

![image](https://user-images.githubusercontent.com/1240716/64478559-ce502280-d15e-11e9-9ae7-bf6c63a5a5a0.png)

This works without Pyrotech because `Terracotta` <-makes- `Clay Block` <-makes- `Clay Ball` -makes-> `Brick` -makes-> `Bricks Block`.

Since Pyrotech removes the recipe for the `Brick` and adds one of its own, the connection no longer works.

The new valid recipe connection would look like this:
`Terracotta` <-makes- `Clay Block` <-makes- `Clay Ball` <-makes- `Lump of Clay` -makes-> `Unfired Brick` -makes-> `Brick` -makes-> `Bricks Block`

Your options are to modify the recipes or modify the FTGU research.

**Comment by God-Arthur** [comment]
OK,I see.Thank you very much!!!

**Comment by codetaylor** [comment]
You're welcome :)
