### ISSUE TITLE
Flint and Tinder has 1 more use than it should have

### ISSUE THREAD

**Issue by Mike-U5** [codetaylor/pyrotech#233]
The Flint and Tinder should (by default) have 8 uses.
It actually has 9. When used at 1 durability, it'll drop to 0 rather than breaking like it should. 

It does when used at 0 durability.

**Comment by Trinsdar** [comment]
yah that whole breaking at 0 bug is a minecraft bug, kinda hard to do anything about it except maybe set the max durability to 7 instead of 8. that's just my opinion on it though, I can't say whether codetaylor has any card up his sleve for that or anything

**Comment by codetaylor** [comment]
The Flint and Tinder, by default, has `9` uses because it is configured with a durability of `8` and adheres to the same behavior as the vanilla tools regarding durability, damage, and breaking.

If you want to change the item's durability, it can be changed in the `module.Ignition.cfg` configuration file:

```
        # The durability of the flint and tinder.
        # Default: 8
        # Min: 1
        # Max: 32767
        I:FLINT_AND_TINDER_DURABILITY=8
```
