### ISSUE TITLE
Error popping up once the bloom has been mined with the hammer

### ISSUE THREAD

**Issue by HazardSkii** [codetaylor/pyrotech#242]
**Issue Description**

An error message pops up every time I use a hammer on a bloom and I am unsure what it means or how to fix it if possible.

**What Happens**

For example, whenever I finish using my hammer on the bloom and the bloom disappears I get this error message that pops up every time.

**Crash Log**

https://paste.dimdev.org/focohikaca.mccrash

**Affected Versions**

- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847
- CraftTweaker: 4.1.19
- Dropt: 1.16.1
- Pyrotech: 1.4.10
- Athenaeum: 1.17.4

**Comment by codetaylor** [comment]
Thanks for the report!

When the hammer power of one swing is powerful enough to complete more than one recipe cycle on the bloom, it will wrap around and complete the recipe again until the power of the swing is used up. When the powerful swing is at the end of the blooms life, it tries to complete the recipe again with an empty input bloom.

This is fixed in `1.4.11` and will be available soon.
