### ISSUE TITLE
Bellows accelerates fuel consumption but not process.

### ISSUE THREAD

**Issue by Roonas** [codetaylor/pyrotech#25]
**Issue Description**
Using a bellows in conjunction with a stone crucible causes the fuel to be expended rapidly, but not the melting itself. 

**What You Expect to Happen**
Bellows accelerates process and fuel consumption 1:1.

**What Actually Happens.**
In my test case, 3 charcoal (4mins) is used nearly instantly when attempting to melt down a clay block (3mins), but the block does not melt, even after attempting the process with over double the amount fuel that _should_ be required.

Script
N/A

Crash Log
N/A

Affected Versions
Minecraft: 1.12.2
Forge: forge1.12.2-14.23.5.2836
Dropt: 1.14.0
Pyrotech: 1.0.4
Athenaeum: 1.17.1

**Comment by Roonas** [comment]
On further inspection, it seems like the crucible is either trying to melt down each item individually, and taking that time frame, or is consuming an infinite amount of fuel if the amount of fluid that would be made exceeds the tanks capacity.

**Comment by codetaylor** [comment]
The crucible has two modes that can be set in the config: synchronous an asynchronous.

By default the crucible is configured in the asynchronous mode which means that it will attempt to melt all input items at the same time within the duration given for the recipe. If the crucible cannot store the amount of liquid that would be produced, the recipe does not progress.

Synchronous operation means that the crucible will do the opposite, melt each item one at a time and each item will take the duration given for the recipe. It will stop progressing recipes again when the amount of liquid produced would exceed the crucible's capacity.

The asynchronous mode needs some adjustment because of the very reason you reported. It is confusing to players. In fact, I was testing something just the other day and couldn't figure out why the crucible wasn't working. Then I remembered.

I think it would be better if, in asynchronous mode, the crucible melted the maximum number of items it could, without exceeding its capacity. This could be achieved by restricting the crucible's input. It would then only allow as many input items as it can hold the results for.

**Comment by Roonas** [comment]
That seems like an appropriate solution, it seems that the soaking pot suffers this issue as well with being able to insert more items than it can create, causing the recipe to not start either. This would be a great fix for both of these and would be _far_ less confusing for users!

**Comment by codetaylor** [comment]
The crucible and soaking pot input interactions have been redesigned in 1.12.2-1.2.0
