### ISSUE TITLE
Incompatibility with Biomes-o-Plenty Wood

### ISSUE THREAD

**Issue by Derpercoaster** [codetaylor/pyrotech#297]
I have come to realize that the new types n wood supplied with the mod "Biomes-o-Plenty" are not compatible with the chopping block or the sawmill. I have tried several different methods to include them as recipes, but it doesn't seem to be possible. It would be great if wood types from other mods were compatible with Pyrotech.

**Comment by codetaylor** [comment]
Pyrotech has pretty good wood compatibility and it should work with most wood types.

Have you gone through the wood compat docs? https://pyrotech.readthedocs.io/en/latest/woodcompat/

You may have to refresh your `core.compat.Wood-Custom.json` file.

You mention you've tried several methods to add wood, what methods have you tried?

**Comment by Derpercoaster** [comment]
Well, I tried adding the recipe for the planks of the wood to the whitelist of the workbench (which I think is supposed to force it to allow it?), but I could not figure out how to use it on the chopping block (it would not allow me to place anything there, and instead allowed the vanilla crafting grid to accept the wood, which it shouldn't do).  
Also, I didn't know there were "docs" of anything

**Comment by Derpercoaster** [comment]
As a side note, is it possible to disable the crafting table recipe override, so I could use the vanilla recipe for making the table?

**Comment by codetaylor** [comment]
> As a side note, is it possible to disable the crafting table recipe override, so I could use the vanilla recipe for making the table?

Yes, using CraftTweaker you can replace the recipe with your own.

Pyrotech doesn't touch recipes added by other mods, ie. log to plank recipes or plank to slab recipes. If you don't want those to work in the vanilla crafting grid, you'll have to remove them with CraftTweaker.

If the chopping block is not accepting wood, it is likely because you either need to restart after running Pyrotech once, or refresh your `core.compat.Wood-Custom.json` file.

**Comment by Derpercoaster** [comment]
Refresh means to delete it right? (Since it replaces it automatically if it's not there). 
And to clarify, the chopping block only does not accept wood from other mods (so vanilla wood is fine)

**Comment by codetaylor** [comment]
Or copy the contents of the generated file to the custom file. If you delete the file, you'll have to restart twice, once for it to generate the file and again to read it.

**Comment by Derpercoaster** [comment]
Wait, do I have to make a file specifically for the wood provided by my other mods? Sorry, I haven't really messed with mod files before, so I have no idea what they do.

**Comment by Derpercoaster** [comment]
Edit: I figured it out. It seems to be working now.

**Comment by codetaylor** [comment]
You're welcome to join the Discord server if you have any more questions: http://discord.codetaylor.com

**Comment by Derpercoaster** [comment]
And I don't think the CraftTweaker thing really answered my other question. I meant that, since Pyrotech removes the vanilla recipe for the crafting table, I wanted to prevent it from doing so, since I don't want to wait for so long to get an iron block for it.

**Comment by codetaylor** [comment]
Pyrotech adds a recipe that overrides the vanilla recipe for the crafting table. To change it back, use CraftTweaker to override the recipe and set it back to the vanilla recipe, or whatever you want. There isn't a way to prevent Pyrotech from overriding the recipe.

**Comment by 0IzzyJ0** [comment]
[BOP-Pyrotech - Copy.txt](https://github.com/codetaylor/pyrotech/files/4549750/BOP-Pyrotech.-.Copy.txt)

Just made a Crafttweaker patch for it, took me like 10 minutes. Github doesn't support .zs files, so I changed it to a .txt. You'll have to change it back, but otherwise this should fix the logs being incompatible. Just instann craftweaker if you haven't already, and throw this in the 'scripts' folder after that's done.
