### ISSUE TITLE
Worktable gamestage support

### ISSUE THREAD

**Issue by MasterEnderman** [codetaylor/pyrotech#3]
Please add gamestage support to the worktable to set different stages for crafting recipes.

**Comment by codetaylor** [comment]
I've implemented GameStages support for the worktable recipes like this:

```java
import mods.pyrotech.Stages;
import mods.pyrotech.Worktable;

Worktable.buildShaped(<minecraft:furnace>, [
  [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>],
  [<minecraft:cobblestone>, null, <minecraft:cobblestone>],
  [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]])
  .setRecipeGameStages(Stages.and(["a", "b"]))
  .register();
```

It uses the same `Stages` as the device restricting methods.

Since the worktable can automagically make anything that the vanilla crafting table can make, I'm pretty sure it will allow you to craft things that are restricted in the vanilla table with the mod RecipeStages. I think it will show those recipes in JEI as well. This hasn't been tested though, I'm just speculating.

Currently, if you wanted to use RecipeStages and have the same gamestage restrictions for a vanilla table's recipe, you'd have to:
* set the recipe stages for the vanilla table recipe, 
* blacklist that recipe from Pyrotech's (Pt) worktable, 
* then create a new duplicate recipe for Pt's worktable with the same game stages.

In the future, maybe I can work out some kind of compat with the RecipeStages mod, but that would be a new feature request.
