### ISSUE TITLE
Some idea to add or not

### ISSUE THREAD

**Issue by LokyLive** [codetaylor/pyrotech#78]
Hello i'm really kind of this mod and i get some idea that could be great for it. 

1=  An early game inconfortable bed, easier to craft than the vanilla (for example dried plant & slab) but give you some debuff on wake up cause you've get a bad night xD

2= Add leather processing for more first armor difficulty

3= Add some Dryed food

4=Add a crude sword ?

5=Add an enchanting table for enchant lvl 1-10 

6=Add early brewing system

7= Early game shear just provide string when used on sheep

8 = Add building block with Masonry Brick and Refractory Block (wall/stairs/slabs/button)

9= Add lantern ( can't being turn off by rain )

10= Add Craftweaker support ? (already planned maybe ) 

11= Add in world bone deposit  like rock but spawning in cave 

12 = Glass shard can be obtained by breaking glass

13=  Add Glue (ore:slimeball)  to craft Sticky items (piston or new sticky item ect ...) and Composite plank using soaking pot and Wood chips

14= Add doghouse to rest our pet 

15= Mushroom pot to create a farm to prtotect them from lightlevel restrictions

Like the title says it's just some idea , of course you're free to use it or not. I' just curious to see wich idea you liked or not ^^

**Comment by codetaylor** [comment]
Thank you for the awesome suggestions! :) I like them.

Pyrotech does already have fairly comprehensive CraftTweaker support for its devices and mechanics. The ZenScript documentation can be found here: https://pyrotech.readthedocs.io/en/latest/

**Comment by LokyLive** [comment]
oO nice site !!! thanks !

**Comment by AnotherVagabond** [comment]
RE: Leather; There's a mod called Leather Works that actually does a fairly good job of this already, and is compatible with PyroTech. I wouldn't mind seeing CodeTaylor's take on it (plus the textures in Leather Works are a bit iffy), but I've been using it as an alternative for now. Most animals give hides, which you have to strip with flint, then you have to strip bark from logs (also with flint), craft them into tannins, put those into a barrel with water, then soak the hides, and dry them on a drying rack. You can also craft leather into small backpacks (I think they hold about 12 items or so), and I find at least a smallish backpack pretty much mandatory for most mods and packs, since most of them add more items that fill up your inventory.

There are a few minor issues: namely that you have to use the mod's drying rack to dry leather instead of the PyroTech drying racks, and also once you strip a log of its bark, you can then craft it into 4 planks via the normal method, which is a bit of a cheat (though that only matters on a server, unless you have terrible willpower). Otherwise, it works pretty well for now, for the most part.

**Comment by LokyLive** [comment]
@AnotherVagabond , i've already tryed it , Jei support won't works for me and i will wait to get more cfg option to use it ,so i will add processing with crafttweaker/contenttweaker .

I'm still thinking the feature could be easily added to pyrotech  and really matching to the mod  too in my opinion

**Comment by codetaylor** [comment]
Thank you for your suggestions. Your feedback is important.

This issue is being closed because it violates one or more of the feature request guidelines found in this project's [README.md](https://github.com/codetaylor/pyrotech):

> * Use an issue title that clearly and concisely describes your idea. Do not prefix your issue title with `[Suggestion]`, `[Idea]`, or `[Request]`. Tags for issues will be selected and applied by project members.

> * Restrict to one request, idea, or suggestion per issue; if you have multiple ideas, create multiple issues. When ideas are separated into individual issues, it is much easier to organize, tag, discuss, and close those individual issues than it is a list of ideas in one issue. Additionally, it is easier for others to check if their idea has already been suggested before posting.

### You are encouraged to read the guidelines and re-submit your ideas.
